Min-Max Heap: mmheap.h File Reference
mmheap.h File Reference
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <cassert>
Functions
size_t parent (size_t i)
size_t has_parent (size_t i)
size_t left (size_t i)
size_t right (size_t i)
size_t gparent (size_t i)
bool has_gparent (size_t i)
bool child (size_t i, size_t c)
uint64_t log_2 (uint64_t i)
bool min_level (size_t i)
std::pair< bool, size_t > min_child (int *heap_array, size_t i, size_t right_index)
std::pair< bool, size_t > min_gchild (int *heap_array, size_t i, size_t right_index)
std::pair< bool, size_t > min_child_or_gchild (int *heap_array, size_t i, size_t right_index)
std::pair< bool, size_t > max_child (int *heap_array, size_t i, size_t right_index)
std::pair< bool, size_t > max_gchild (int *heap_array, size_t i, size_t right_index)
std::pair< bool, size_t > max_child_or_gchild (int *heap_array, size_t i, size_t right_index)
void mmheap_sift_down_min (int *heap_array, size_t sift_index, size_t right_index)
void mmheap_sift_down_max (int *heap_array, size_t sift_index, size_t right_index)
void mmheap_sift_down (int *heap_array, size_t sift_index, size_t right_index)
void bubble_up_min (int *heap_array, size_t bubble_index)
void bubble_up_max (int *heap_array, int bubble_index)
void bubble_up (int *heap_array, int bubble_index)
void make_mm_heap (int *heap_array, size_t size)
make an arbitrary array into a heap (in-place)
void mm_heap_add (int value, int *heap_array, size_t &count, size_t max_size)
int mm_heap_max (int *heap_array, size_t count)
int mm_heap_min (int *heap_array, size_t count)
std::pair< bool, int > mm_heap_ripple_add (int value, int *heap_array, size_t &count, size_t max_size)
add to heap, pushing the maximum value out if the heap is full
int mm_heap_replace_at_index (int new_value, size_t index, int *heap_array, size_t count)
int mm_heap_remove_at_index (size_t index, int *heap_array, size_t &count)
int mm_heap_remove_min (int *heap_array, size_t &count)
int mm_heap_remove_max (int *heap_array, size_t &count)
Detailed Description
Defines functions for maintaining a Min-Max Heap, as described by Adkinson: M. D. Atkinson, J.-R. Sack, N. Santoro, and T. Strothotte. 1986. Min-max heaps and generalized priority queues. Commun. ACM 29, 10 (October 1986), 996-1000. DOI=http://dx.doi.org/10.1145/6617.6621
Author
Jason L Causey Released under the MIT License: http://opensource.org/licenses/MIT
Copyright
Copyright (c) 2015 Jason L Causey, Arkansas State University
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file mmheap.h.
Function Documentation
void bubble_up (int * heap_array, int bubble_index)
perform min-max heap bubble-up on an element (at bubble_index)
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Definition at line 356 of file mmheap.h.
References bubble_up_max(), bubble_up_min(), has_parent(), min_level(), and parent().
void bubble_up_max (int * heap_array, int bubble_index)
perform min-max heap bubble-up on an element (at bubble_index) that is on a max-level
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Definition at line 338 of file mmheap.h.
References gparent(), and has_gparent().
Referenced by bubble_up().
void bubble_up_min (int * heap_array, size_t bubble_index)
perform min-max heap bubble-up on an element (at bubble_index) that is on a min-level
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Definition at line 320 of file mmheap.h.
Referenced by bubble_up().
bool child (size_t i, size_t c) inline
Definition at line 47 of file mmheap.h.
size_t gparent (size_t i) inline
Definition at line 45 of file mmheap.h.
Referenced by bubble_up_max().
bool has_gparent (size_t i) inline
Definition at line 46 of file mmheap.h.
Referenced by bubble_up_max().
size_t has_parent (size_t i) inline
Definition at line 42 of file mmheap.h.
Referenced by bubble_up().
size_t left (size_t i) inline
Definition at line 43 of file mmheap.h.
uint64_t log_2 (uint64_t i)
Definition at line 55 of file mmheap.h.
void make_mm_heap (int * heap_array, size_t size)
make an arbitrary array into a heap (in-place)
Applies Floyd's algorithm (adapted to a min-max heap) to produce a heap from an arbitrary array in linear time.
Parameters
heap_array the array that will become a heap
size the number of elements in the array
Definition at line 385 of file mmheap.h.
std::pair<bool, size_t> max_child (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-child
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child whose value is largest (only if the first element is true)
Definition at line 171 of file mmheap.h.
std::pair<bool, size_t> max_child_or_gchild (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child or grandchild containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-(grand)child
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child or grandchild whose value is largest (only if the first element is true)
Definition at line 227 of file mmheap.h.
std::pair<bool, size_t> max_gchild (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any grandchildren, and if so, the index of the grandchild containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-grandchild
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has grandchildren (false otherwise), and the second element is the index of the grandchild whose value is largest (only if the first element is true)
Definition at line 195 of file mmheap.h.
std::pair<bool, size_t> min_child (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-child
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child whose value is smallest (only if the first element is true)
Definition at line 96 of file mmheap.h.
std::pair<bool, size_t> min_child_or_gchild (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child or grandchild containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-(grand)child
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child or grandchild whose value is smallest (only if the first element is true)
Definition at line 151 of file mmheap.h.
std::pair<bool, size_t> min_gchild (int * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any grandchildren, and if so, the index of the grandchild containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-grandchild
right-index the index of the right-most element that is part of the heap
Returns
a pair where the first element is true if i has grandchildren (false otherwise), and the second element is the index of the grandchild whose value is smallest (only if the first element is true)
Definition at line 119 of file mmheap.h.
bool min_level (size_t i) inline
returns true if i is on a Min-Level
Parameters
i index into the heap
Returns
true if i is on a min-level
Definition at line 81 of file mmheap.h.
Referenced by bubble_up().
void mm_heap_add (int value, int * heap_array, size_t & count, size_t max_size)
add a new value to the heap (and update the count)
Parameters
value the new value to add
heap_array the heap
[in,out] count the current number of items in the heap (will update)
max_size the physical storage allocation size of the heap
Exceptions
std::runtime_error if the heap is full prior to the add operation
Definition at line 402 of file mmheap.h.
int mm_heap_max (int * heap_array, size_t count)
get the maximum value in the heap
Parameters
heap_array the heap
count the current number of values contained in the heap
Returns
the maximum value in the heap
Exceptions
std::runtime_error if the heap is empty
Definition at line 421 of file mmheap.h.
int mm_heap_min (int * heap_array, size_t count)
get the minimum value in the heap
Parameters
heap_array the heap
count the current number of values contained in the heap
Returns
the minimum value in the heap
Exceptions
std::runtime_error if the heap is empty
Definition at line 438 of file mmheap.h.
int mm_heap_remove_at_index (size_t index, int * heap_array, size_t & count)
remove and return value at a given index
Parameters
index index to remove
heap_array the heap
[in,out] count current number of values in the heap (will update)
Returns
the value being removed
Exceptions
std::runtime_error if the heap is empty
std::range_error if the index is out of range
Definition at line 538 of file mmheap.h.
int mm_heap_remove_max (int * heap_array, size_t & count)
remove and return the maximum value in the heap
Parameters
heap_array the array
count the current number of values in the heap (will update)
Returns
the maximum value in the heap
Exceptions
std::runtime_error if the heap is empty
Definition at line 579 of file mmheap.h.
int mm_heap_remove_min (int * heap_array, size_t & count)
remove and return the minimum value in the heap
Parameters
heap_array the array
count the current number of values in the heap (will update)
Returns
the minimum value in the heap
Exceptions
std::runtime_error if the heap is empty
Definition at line 559 of file mmheap.h.
int mm_heap_replace_at_index (int new_value, size_t index, int * heap_array, size_t count)
replace and return the value at a given index with a new value
Parameters
new_value new value to insert
index index of the value to replace
heap_array the heap
count number of values currently stored in the heap
Returns
the old value being replaced
Exceptions
std::runtime_error if the heap is empty
std::range_error if the index is out of range
Definition at line 493 of file mmheap.h.
std::pair<bool, int> mm_heap_ripple_add (int value, int * heap_array, size_t & count, size_t max_size)
add to heap, pushing the maximum value out if the heap is full
Add to the min-max heap in such a way that the maximum value is removed at the same time if the heap has reached its storage capacity.
Parameters
value new value to add
heap_array the heap
[in,out] count number of values currently in the heap (will update)
max_size maximum physical size allocated for the heap
Returns
a pair consising of a flag and a value; the first element is a flag indicating that overflow occurred, and the second element is the value that shifted out of the heap (formerly the maximum) when the new value was added (set only if an overflow occurred)
Definition at line 460 of file mmheap.h.
void mmheap_sift_down (int * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index)
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Definition at line 305 of file mmheap.h.
void mmheap_sift_down_max (int * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index) that is on a max-level
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Definition at line 274 of file mmheap.h.
void mmheap_sift_down_min (int * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index) that is on a min-level
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Definition at line 243 of file mmheap.h.
size_t parent (size_t i) inline
Definition at line 41 of file mmheap.h.
Referenced by bubble_up().
size_t right (size_t i) inline
Definition at line 44 of file mmheap.h.