Min-Max Heap: _mmheap Namespace Reference
_mmheap Namespace Reference
Functions
size_t parent (size_t i)
size_t has_parent (size_t i)
size_t left (size_t i)
size_t right (size_t i)
size_t gparent (size_t i)
bool has_gparent (size_t i)
bool child (size_t i, size_t c)
uint64_t log_2 (uint64_t i)
bool min_level (size_t i)
template<typename DataType >
std::pair< bool, size_t > min_child (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
std::pair< bool, size_t > min_gchild (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
std::pair< bool, size_t > min_child_or_gchild (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
std::pair< bool, size_t > max_child (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
std::pair< bool, size_t > max_gchild (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
std::pair< bool, size_t > max_child_or_gchild (DataType *heap_array, size_t i, size_t right_index)
template<typename DataType >
void sift_down_min (DataType *heap_array, size_t sift_index, size_t right_index)
template<typename DataType >
void sift_down_max (DataType *heap_array, size_t sift_index, size_t right_index)
template<typename DataType >
void sift_down (DataType *heap_array, size_t sift_index, size_t right_index)
template<typename DataType >
void bubble_up_min (DataType *heap_array, size_t bubble_index)
template<typename DataType >
void bubble_up_max (DataType *heap_array, int bubble_index)
template<typename DataType >
void bubble_up (DataType *heap_array, int bubble_index)
Detailed Description
The _mmheap namespace contains functions that are only intended for internal use by the "public-facing" functions in the mmheap namespace. None of the functions in _mmheap:: should be necessary externally.
Function Documentation
template<typename DataType > void _mmheap::bubble_up (DataType * heap_array, int bubble_index)
perform min-max heap bubble-up on an element (at bubble_index)
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 419 of file mmheap.h.
References has_parent(), min_level(), and parent().
template<typename DataType > void _mmheap::bubble_up_max (DataType * heap_array, int bubble_index)
perform min-max heap bubble-up on an element (at bubble_index) that is on a max-level
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 397 of file mmheap.h.
References gparent(), and has_gparent().
template<typename DataType > void _mmheap::bubble_up_min (DataType * heap_array, size_t bubble_index)
perform min-max heap bubble-up on an element (at bubble_index) that is on a min-level
Parameters
heap_array the heap
bubble_index the index of the element that should be bubbled up
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 375 of file mmheap.h.
bool _mmheap::child (size_t i, size_t c) inline
Definition at line 63 of file mmheap.h.
size_t _mmheap::gparent (size_t i) inline
Definition at line 61 of file mmheap.h.
Referenced by bubble_up_max().
bool _mmheap::has_gparent (size_t i) inline
Definition at line 62 of file mmheap.h.
Referenced by bubble_up_max().
size_t _mmheap::has_parent (size_t i) inline
Definition at line 58 of file mmheap.h.
Referenced by bubble_up().
size_t _mmheap::left (size_t i) inline
Definition at line 59 of file mmheap.h.
uint64_t _mmheap::log_2 (uint64_t i)
Definition at line 71 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::max_child (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-child
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child whose value is largest (only if the first element is true)
Definition at line 203 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::max_child_or_gchild (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child or grandchild containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-(grand)child
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child or grandchild whose value is largest (only if the first element is true)
Definition at line 266 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::max_gchild (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any grandchildren, and if so, the index of the grandchild containing the maximum value.
Parameters
heap_array the heap
i the index (parent) for which to find the max-grandchild
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has grandchildren (false otherwise), and the second element is the index of the grandchild whose value is largest (only if the first element is true)
Definition at line 230 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::min_child (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-child
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child whose value is smallest (only if the first element is true)
Definition at line 116 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::min_child_or_gchild (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any children, and if so, the index of the child or grandchild containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-(grand)child
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has children (false otherwise), and the second element is the index of the child or grandchild whose value is smallest (only if the first element is true)
Definition at line 179 of file mmheap.h.
template<typename DataType > std::pair<bool, size_t> _mmheap::min_gchild (DataType * heap_array, size_t i, size_t right_index)
get a pair considing of an indication of whether i has any grandchildren, and if so, the index of the grandchild containing the minimum value.
Parameters
heap_array the heap
i the index (parent) for which to find the min-grandchild
right-index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Returns
a pair where the first element is true if i has grandchildren (false otherwise), and the second element is the index of the grandchild whose value is smallest (only if the first element is true)
Definition at line 143 of file mmheap.h.
bool _mmheap::min_level (size_t i) inline
returns true if i is on a Min-Level
Parameters
i index into the heap
Returns
true if i is on a min-level
Definition at line 97 of file mmheap.h.
Referenced by bubble_up().
size_t _mmheap::parent (size_t i) inline
Definition at line 57 of file mmheap.h.
Referenced by bubble_up().
size_t _mmheap::right (size_t i) inline
Definition at line 60 of file mmheap.h.
template<typename DataType > void _mmheap::sift_down (DataType * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index)
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 356 of file mmheap.h.
template<typename DataType > void _mmheap::sift_down_max (DataType * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index) that is on a max-level
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 321 of file mmheap.h.
template<typename DataType > void _mmheap::sift_down_min (DataType * heap_array, size_t sift_index, size_t right_index)
perform min-max heap sift-down on an element (at sift_index) that is on a min-level
Parameters
heap_array the heap
sift_index the index of the element that should be sifted down
right_index the index of the right-most element that is part of the heap
Template Parameters
DataType the type of data stored in the heap - must be LessThanComparable, Swappable, CopyConstructable, and CopyAssignable
Definition at line 286 of file mmheap.h.